Guest registration
harperiscoding/Women-in-Chemistry-Initiative-WICI pull request #24
Opened 2019-04-10 04:40 UTC by townsend3721

2019-04-10 05:01 UTC, harperiscoding requested changes

2019-04-10 05:01 UTC, walkerspence commented on app/controllers/guests_controller.rb
> +		if @guest.firstname.blank?
these checks should all be done through model validations.

2019-04-10 05:01 UTC, walkerspence commented on app/helpers/guests_helper.rb
> +module GuestsHelper
delete unused file

2019-04-10 05:01 UTC, walkerspence commented on app/models/guest.rb
> +class Guest < ApplicationRecord
no relation

2019-04-11 07:23 UTC, harperiscoding approved these changes

2019-04-11 08:07 UTC, nicolepb requested changes
this is better, just probably clean the indents in guests_controller so it's more readable

2019-04-11 08:07 UTC, nicolepb commented on app/controllers/guests_controller.rb
> +
I'm not sure why it's indented weirdly, it's a little confusing, maybe just fix this

2019-04-11 18:46 UTC, merged