Event pictures
harperiscoding/Women-in-Chemistry-Initiative-WICI pull request #48
Opened 2019-04-26 03:39 UTC by townsend3721

Added photo uploading for events

2019-04-26 06:53 UTC, harperiscoding requested changes

2019-04-26 06:53 UTC, walkerspence commented on spec/controllers/events_controller_spec.rb
>    let!(:fut_event) { FactoryGirl.create(:future_event, id: 2) }
try to only put let statements in blocks they're necessary in. check out my branch for some ideas.

2019-04-26 06:53 UTC, walkerspence commented on spec/controllers/events_controller_spec.rb
>    let!(:fut_event) { FactoryGirl.create(:future_event, id: 2) }
this will prevent you from having to change the expect statement for index as well.

2019-04-29 08:29 UTC, dantoth24 commented
![image](https://user-images.githubusercontent.com/31327276/56884263-0e1f3480-6a1e-11e9-95eb-db8bc67cb475.png) This error should not be displayed to the user. Also, the image I tried to upload was a 400x400 jpg, shouldn't that work?

2019-04-29 08:50 UTC, dantoth24 commented
Got it to work by installing ImageMagic. Make sure to take note what external software is needed.
![image](https://user-images.githubusercontent.com/31327276/56885042-53dcfc80-6a20-11e9-831d-368693767e5f.png)
To make this UI more clear remove photo should be next to the checkmark instead of the image.

![image](https://user-images.githubusercontent.com/31327276/56885134-8dae0300-6a20-11e9-9396-1db662443c46.png)
Remove the table row name Picture:

2019-04-29 19:59 UTC, townsend3721 commented
Fixed the clunkiness, added stuff to the readme for downloading image kick

2019-04-29 21:09 UTC, closed without merging