Donate page
harperiscoding/Women-in-Chemistry-Initiative-WICI pull request #70
Opened 2019-05-10 17:55 UTC by townsend3721

Cleaned up the two donation views.  After this gets merged, I will make a separate branch to the hide the views.

2019-05-10 19:17 UTC, nicolepb approved these changes
Looks good and secure how they wanted it

2019-05-10 20:54 UTC, dantoth24 requested changes
![image](https://user-images.githubusercontent.com/31327276/57556075-db811000-732a-11e9-959b-fcafefaf3bd3.png)
Maybe its a matter of opinion, but I think this looks pretty sketchy. I think when it comes to making the form look trustworthy it should be clean and professional rather than so in-your-face about being legit. Perhaps the logo could stay, but it should be much smaller.

2019-05-10 21:26 UTC, walkerspence commented
![image](https://user-images.githubusercontent.com/20048451/57557567-8267ab00-732f-11e9-9951-87f449da6f8b.png)
the box for entering amount does not need to be this big, and does not need to be shoved right next to the donate button.

2019-05-10 22:13 UTC, townsend3721 commented
<img width="461" alt="Screen Shot 2019-05-10 at 3 11 25 PM" src="https://user-images.githubusercontent.com/46975902/57559328-23596480-7336-11e9-9f94-77d8ffe586b9.png">
<img width="468" alt="Screen Shot 2019-05-10 at 3 11 40 PM" src="https://user-images.githubusercontent.com/46975902/57559337-2bb19f80-7336-11e9-98d0-f959e61f2cf1.png">
 Which one of these do you think looks better

2019-05-11 01:21 UTC, dantoth24 requested changes
It looks good, but as Walker said in the slack, you need to make it so the footer is not visible unless you scroll down. This can usually be done by adding some padding.

2019-05-11 02:03 UTC, dantoth24 commented on app/views/donations/index.html.erb
> +			<%= image_tag("https://scontent-sjc3-1.xx.fbcdn.net/v/t31.0-8/10355612_1466423220317340_2509667441501223212_o.png?_nc_cat=109&_nc_ht=scontent-sjc3-1.xx&oh=a0a3aa854e49d3c92d30d3063a42bc74&oe=5D605
You should download the image and link to it locally rather than wherever this is. There's no guarantee this link will always be working.

2019-05-11 21:51 UTC, walkerspence commented
I like the second: reverse the order of the "Donate $" and the text field, and put the "$" in front of the text field and not in the button.

2019-05-12 04:45 UTC, dantoth24 approved these changes

2019-05-12 07:22 UTC, harperiscoding requested changes
You did something that changed the font size of the header - don't do that.

2019-05-12 07:22 UTC, walkerspence commented on app/views/donations/index.html.erb
> +  			<%= text_field_tag :amount_dollars, 0, class: "donatetext", style: "border-radius: 5px; padding-left: 20px;"%>
Dollar sign is misaligned in here 
![image](https://user-images.githubusercontent.com/20048451/57579083-d7004880-744b-11e9-84b6-d32f47eacdbc.png)

2019-05-12 07:22 UTC, walkerspence commented on app/assets/stylesheets/donations.scss
> +}
fix all indentation in this file, remove all !important flags from donations file, especially for stuff that should be standard sitewide like buttons. Whenever you use !important it overrides it any time that class is used elsewhere.

2019-05-12 07:22 UTC, walkerspence commented on app/views/donations/new.html.erb
> +  <%= submit_tag "Confirm", id: :confirm, class: "buttonsubmit", style: "font-size: 15px; align: left;" %>
confirm buttons should be below the amount.

2019-05-12 20:33 UTC, dstephens3 commented
I pulled your branch and everything looks good layoutwise but you still need to change your color scheme to match the rest of the website

2019-05-12 22:12 UTC, harperiscoding reviewed
also, images go in assets/images and should have real names.

2019-05-13 01:01 UTC, harperiscoding requested changes
This cannot be merged until those !important flags are gone. You should be using the same buttons that appear everywhere else on the website. 

![image](https://user-images.githubusercontent.com/20048451/57590432-8e469f00-74e0-11e9-99a6-a21c4d20031e.png)

1. shouldn't be misaligned
2. should be a circle
3. should not be transparent; see my last branch for a powered by stripe logo 
4. should be white
5. Donate buttons should all be the same kind of button as appears elsewhere on the site. Perhaps use a secondary button for the donate custom amount and primaries for the rest.

![image](https://user-images.githubusercontent.com/20048451/57590517-33617780-74e1-11e9-88e1-be5216a56101.png)

1. Put this next to the total amount, otherwise the naked link looks very sloppy.
2. Confirm buttons always on the right, back buttons always on the left. 
3. green text doesn't work for contrast. Look at my last branch for an example of how to make a checkout card


Also, there should be a back button on the bottom of both pages and you've done something that made the header too big.

2019-05-14 03:14 UTC, harperiscoding requested changes
You messed up merge conflict resolution big time, and there's still a ton of inline styles.

2019-05-14 03:14 UTC, walkerspence commented on Gemfile
> -  gem 'seed_dump'
don't remove this gem

2019-05-14 03:14 UTC, walkerspence commented on app/assets/stylesheets/application.css
> -.content-card {
definitely don't remove these- they are used everywhere in the site

2019-05-14 03:14 UTC, walkerspence commented on app/assets/stylesheets/events.scss
> -}
don't remove this either.

2019-05-14 03:14 UTC, walkerspence commented on app/assets/stylesheets/events.scss
> +
I think you messed up the merge conflict resolution. these were removed and put in application.scss because more pages were using them.

2019-05-14 03:14 UTC, walkerspence commented on app/assets/stylesheets/guests.scss
> -
created with the express purpose of making payments easier. these must remain.

2019-05-14 03:14 UTC, walkerspence commented on app/controllers/guests_controller.rb
> -        flash.now[:alert] = "We're sorry, this event is at capacity."
again, this was my commit. must remain.

2019-05-14 03:14 UTC, walkerspence commented on app/controllers/guests_controller.rb
> -      params.require(:guest).permit(:first_name, :last_name, :email, :occupation, :gender, :department)
must remain.

2019-05-14 03:14 UTC, walkerspence commented on app/models/guest.rb
> -  validates :first_name, :last_name, presence: true
must remain.

2019-05-14 03:14 UTC, walkerspence commented on app/views/about/index.html.erb
> +      <div class="event-card card bg-card text-white">
must remain.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +<div align="center" style= "padding-top: 20px; border: solid; background: #0F4040; color: #0F4040; border-width: .5px;" >
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +<div class="container-fluid" style="padding-top: 2%; margin-top: 7%; background: #2E8C8C; width: 30%; float: left; border: solid; border-width: 1px; border-color: #0F4040; border-radius: 5px; margin-
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +		<div class="container-fluid" style="margin-top: 5%; padding-bottom: 10%; width: 30%; float: right; margin-right: 20%">
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +			<div class="container-fluid" style= "background: #ffffff; border-radius: 50%; padding-top: 15%; width: 420px; height: 420px; margin-bottom: 3%;">
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +			<div style= "float:left; font-size: 12px; color: #ffffff">
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +			<%= link_to "https://501c3go.com/what-is-a-501c3/", style: "font-size: 12px" %>
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +	<h1 class="container-fluid" style="padding-bottom: 1%; border-bottom: solid; border-bottom-width: 1px; border-bottom-color: #ffffff">
remove unnecessary inline styles.

2019-05-14 03:14 UTC, walkerspence commented on app/views/donations/index.html.erb
> +	<div class="container-fluid" style= "color: #ffffff;"> Proceeds go towards the Women in Chemistry Initiative </div>
remove unnecessary inline styles. you get the gist.

2019-05-14 03:14 UTC, walkerspence commented on app/views/events/_card.html.erb
> -<div class="content-card card bg-card text-white" id="event_<%= event.id %>">
bad merge conflict. gonna stop commenting these + inline styles.

2019-05-14 04:40 UTC, closed without merging